sudo: false
language: node_js
node_js:
  - '4'

cache: npm

before_install:
  - openssl aes-256-cbc -K $encrypted_d7212df6fd0a_key -iv $encrypted_d7212df6fd0a_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - npm install

script:
  - npm run build

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
  - echo $TRAVIS_COMMIT > $TRAVIS_BUILD_DIR/build/DEPLOYED_COMMIT.txt

deploy:
  skip_cleanup: true
  provider: script
  script: rsync -zvr -e "ssh -o StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR/build/ $SSH_USER@newc-web.new.ox.ac.uk:~/website
  on:
    branch: master
